# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

# Set GITHUB_TOKEN
builds:
  - skip: false
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.Version={{.Version}} -s -f

release:
  disable: false
  prerelease: auto
  mode: keep-existing

brews:
  - tap:
      owner: intercloud
      name: homebrew-tap-test
      token: '{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}'
    license: MPL
    folder: Formula
    # Uncomment for private repositoris
    # download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    # custom_require: lib/custom_download_strategy
    description: 'Gobinsec'
    homepage: 'https://github.com/intercloud/gobinsec'
    test: |
      system "#{bin}/gobinsec -version"
    install: |
      bin.install "gobinsec"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

# Set env SLACK_WEBHOOK
announce:
  slack:
    enabled: true
    channel: '#console-dev'
    username: Github Release
