#!/usr/bin/env sh
#
# Installation script for Unix platforms. To run installation, type :
#
# $ sh -c "$(curl -L https://github.com/intercloud/gobinsec/releases/latest/download/install)"
#
# or (if you don't have curl installed):
#
# $ sh -c "$(wget -O - https://github.com/intercloud/gobinsec/releases/latest/download/install)"

set -e

log() {
    echo "$@"
}

logF() {
    echo >&2 "$@"
    exit 1
}

repo="gobinsec"
owner="intercloud"
binary="${repo}"

get_os() {
    echo $(uname -s | awk '{print tolower($0)}')
}

get_arch() {
    a=$(uname -m)
    case ${a} in
    "x86_64" | "amd64")
        echo "x86_64"
        ;;
    "i386" | "i486" | "i586")
        echo "i386"
        ;;
    *)
        echo ${NIL}
        ;;
    esac
}

if [ -z "$githubUrl" ]; then
    githubUrl="https://github.com"
fi

# parse flag
for i in "$@"; do
    case $i in
    -v=* | --version=*)
        version="${i#*=}"
        shift
        ;;
    *)
        # unknown option
        ;;
    esac
done

if [ -z "$version" ]; then
    version="latest"
fi

# get OS and ARCH and build binary name
os=$(get_os)
arch=$(get_arch)

log "os: ${os}"
log "arch: ${arch}"
log "version: ${version:-latest}"

fileName="${binary}_${os}_${arch}.tar.gz"

# set default installation directory
if [ -d "/opt/local/bin" ]; then
    executableFolder="/opt/local/bin"
elif [ -d "/opt/bin" ]; then
    executableFolder="/opt/bin"
elif [ -d "/usr/local/bin" ]; then
    executableFolder="/usr/local/bin"
elif [ -d "/usr/bin" ]; then
    executableFolder="/usr/bin"
else
    executableFolder="/bin"
fi

if command -v curl >/dev/null 2>&1; then
    downloadCmd="curl -sS --fail --location --output "
elif command -v wget >/dev/null 2>&1; then
    downloadCmd="wget --quiet --output-document="
else
    logF "curl or wget is required"
fi

# Set URI to download
assetUri="${githubUrl}/${owner}/${repo}/releases/download/${version}/${fileName}"
if [ "${version}" = "latest" ]; then
    assetUri="${githubUrl}/${owner}/${repo}/releases/latest/download/${fileName}"
fi

downloadFolder="/tmp/${binary}"
mkdir -p ${downloadFolder}
downloadedFile="${downloadFolder}/${fileName}"

log "[1/2] Download ${assetUri}"
$downloadCmd"${downloadedFile}" "${assetUri}"

log "[2/2] Install ${binary} to '${executableFolder}'"
if [ -w "${directory}" ]; then
    tar -xz -f ${downloadedFile} -C ${executableFolder}
    chmod +x ${executableFolder}/${binary}
else
    sudo tar -xz -f ${downloadedFile} -C ${executableFolder}
    sudo chmod +x ${executableFolder}/${binary}
fi

echo "${binary} installed in '${executableFolder}' directory"
