#!/usr/bin/env sh
#
# Installation script for Unix platforms. To run installation, type :
#
# $ sh -c "$(curl -L https://github.com/intercloud/gobinsec/releases/latest/download/install)"
#
# or (if you don't have curl installed):
#
# $ sh -c "$(wget -O - https://github.com/intercloud/gobinsec/releases/latest/download/install)"

set -e

NAME="gobinsec"

# get OS and ARCH and build binary name
os=`uname | tr '[:upper:]' '[:lower:]'`
arch=`uname -m`

if [ "$arch" = "i386" ]; then
    arch="386"
elif [ "$arch" = "x86_64" ]; then
    arch="amd64"
fi

echo "os: ${os}"
echo "arch: ${arch}"

binary="${NAME}-${os}-${arch}"

# set default installation directory
if [ -d "/opt/local/bin" ]
then
    DEFAULT_DIR="/opt/local/bin"
elif [ -d "/opt/bin" ]
then
    DEFAULT_DIR="/opt/bin"
elif [ -d "/usr/local/bin" ]
then
    DEFAULT_DIR="/usr/local/bin"
elif [ -d "/usr/bin" ]
then
    DEFAULT_DIR="/usr/bin"
else
    DEFAULT_DIR="/bin"
fi

# select command to download binary
if hash curl 2>/dev/null
then
    command="curl -L -o"
elif hash wget 2>/dev/null
then
    command="wget -O"
else
    echo "You must install curl or wget to run this installation script"
    exit 1
fi

# download binary in /tmp/${NAME} and make it executable
${command} /tmp/${NAME} https://github.com/intercloud/${NAME}/releases/latest/download/${binary}
chmod +x /tmp/${NAME}

# prompt for installation directory
read -p "Installation directory [${DEFAULT_DIR}]? " directory
if [ -z "$directory" ]
then
    directory=${DEFAULT_DIR}
fi

# copy binary to installation directory
if [ -w "${directory}" ]
then
    mv /tmp/${NAME} ${directory}
else
    sudo mv /tmp/${NAME} ${directory}
    sudo chown root: ${directory}/${NAME}
fi

echo "${NAME} installed in '${directory}' directory"
